# Generated by Django 3.2.2 on 2021-05-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
